import Link from "next/link";
import { SectionHeading } from "@/components/section-heading";
import { services, portfolioItems, blogPosts } from "@/lib/site-data";

export default function HomePage() {
  return (
    <main id="main-content">
      <section className="hero hero--home"><div className="container hero__grid"><div><p className="eyebrow">Website · Admin · Business System</p><h1>홈페이지를 넘어<br /><span>기업의 업무까지</span> 개선합니다.</h1><p className="lead">중소기업의 서비스와 강점을 더 분명하게 보여주고, 문의 이후의 반복 업무까지 하나의 흐름으로 연결합니다.</p><div className="button-row"><Link className="button button--gold" href="/contact">프로젝트 문의</Link><Link className="button button--ghost" href="/diagnosis">무료 홈페이지 진단</Link></div></div><div className="hero-art" aria-hidden="true"><div className="hero-art__window"><i /><i /><i /><span /></div><div className="hero-art__card hero-art__card--one">Strategy</div><div className="hero-art__card hero-art__card--two">Workflow</div></div></div></section>
      <section className="section section--ink"><div className="container"><SectionHeading eyebrow="What We Solve" title="낡은 화면만 바꾸는 것으로는 충분하지 않습니다" description="고객에게 필요한 정보를 전달하고, 접수된 문의가 실제 업무로 이어지는 과정까지 함께 설계합니다." /><div className="problem-grid"><article><b>01</b><h3>설명이 어려운 홈페이지</h3><p>회사와 서비스의 강점이 고객의 질문 순서대로 정리되지 않았습니다.</p></article><article><b>02</b><h3>흩어진 문의와 견적</h3><p>전화, 메일, 메신저와 엑셀에 고객 정보와 처리 기록이 나뉘어 있습니다.</p></article><article><b>03</b><h3>반복되는 수작업</h3><p>접수, 안내, 보고와 후속 업무를 담당자가 매번 다시 처리합니다.</p></article></div></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Core Services" title="지금 필요한 범위부터 시작합니다" description="기업 홈페이지부터 관리자와 맞춤형 업무 시스템까지 단계적으로 확장할 수 있습니다." /><div className="card-grid">{services.map((service, index) => <Link className="service-card" href={`/services/${service.slug}`} key={service.slug}><span>0{index + 1}</span><h3>{service.title}</h3><p>{service.summary}</p><strong>자세히 보기 →</strong></Link>)}</div></div></section>
      <section className="section section--soft"><div className="container split-feature"><div><p className="eyebrow">Website Checkup</p><h2>전체 재제작 전에<br />현재 상태부터 확인하세요.</h2><p>모바일, 속도, 검색 노출, 문의 흐름과 콘텐츠를 기준으로 개선 우선순위를 정리합니다.</p><Link className="text-link" href="/diagnosis">무료 간편진단 신청 →</Link></div><div className="score-card"><span>WEBSITE SCORE</span><strong>5</strong><small>가지 핵심 영역 진단</small></div></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Portfolio" title="문제와 해결과정으로 설명합니다" /><div className="content-grid">{portfolioItems.map((item) => <Link className="content-card" href={`/portfolio/${item.slug}`} key={item.slug}><div className={`visual visual--${item.tone}`}><span>{item.label}</span></div><div><h3>{item.title}</h3><p>{item.summary}</p></div></Link>)}</div><div className="section-action"><Link className="button button--outline" href="/portfolio">포트폴리오 전체 보기</Link></div></div></section>
      <section className="section section--navy"><div className="container split-feature"><div><p className="eyebrow">AI Website Class</p><h2>AI와 함께 직접 만드는<br />홈페이지 제작교육</h2><p>기획부터 공개까지 따라 할 수 있도록 실습 중심으로 진행합니다.</p><Link className="button button--gold" href="/education">교육 과정 확인</Link></div><ol className="step-list"><li><span>01</span>목표와 고객 정리</li><li><span>02</span>AI로 구조와 문구 설계</li><li><span>03</span>반응형 화면 제작</li><li><span>04</span>검수와 공개</li></ol></div></section>
      <section className="section"><div className="container"><SectionHeading eyebrow="Insights" title="실무에 필요한 기준을 공유합니다" /><div className="blog-grid">{blogPosts.slice(0, 3).map((post) => <Link href={`/blog/${post.slug}`} key={post.slug}><span>{post.category}</span><h3>{post.title}</h3><p>{post.summary}</p><strong>글 읽기 →</strong></Link>)}</div></div></section>
      <section className="final-cta"><div className="container"><p className="eyebrow">Start a Project</p><h2>현재 고민부터<br />편하게 알려주세요.</h2><p>범위가 정리되지 않아도 괜찮습니다. 필요한 순서부터 함께 찾겠습니다.</p><Link className="button button--gold" href="/contact">프로젝트 상담 시작</Link></div></section>
    </main>
  );
}
